#!/bin/bash
echo "================================================================"
echo "              ELI CS机器人ROS 2完整使用指南"
echo "================================================================"
echo ""
echo "🌟 编译状态: ✅ 完全成功"
echo "📦 包数量: 8个包全部构建完成"
echo "🕒 构建时间: $(date)"
echo ""
echo "📋 可用功能包列表:"
echo "   1. eli_common_interface      - 通用接口定义"
echo "   2. eli_dashboard_interface   - 仪表板接口"
echo "   3. eli_cs_robot_description  - 机器人描述(URDF)"
echo "   4. eli_cs_robot_driver       - 机器人驱动程序"
echo "   5. eli_cs_controllers        - 自定义控制器"
echo "   6. eli_cs_robot_calibration  - 机器人校准"
echo "   7. eli_cs_robot_moveit_config - MoveIt配置"
echo "   8. eli_cs_robot_simulation_gz - Gazebo仿真"~
echo ""
echo "🚀 快速开始:"
echo ""
echo "1. 设置环境变量:"
echo "   source ~/elite_ros_ws/install/setup.bash"
echo ""
echo "2. 查看机器人模型:"
echo "   ros2 launch eli_cs_robot_description view_cs.launch.py"
echo ""
echo "3. 启动真实机器人控制:"
echo "   ros2 launch eli_cs_robot_driver elite_control.launch.py"
echo ""
echo "4. 启动仿真环境:"
echo "   ros2 launch eli_cs_robot_simulation_gz cs_sim_control.launch.py"
echo ""
echo "5. 使用MoveIt进行运动规划:"
echo "   ros2 launch eli_cs_robot_moveit_config cs_moveit.launch.py"
echo ""
echo "🔧 工具和实用程序:"
echo ""
echo "• Dashboard客户端:"
echo "   ~/elite_ros_ws/install/eli_cs_robot_driver/lib/eli_cs_robot_driver/dashboard_client"
echo ""
echo "• Script节点:"
echo "   ~/elite_ros_ws/install/eli_cs_robot_driver/lib/eli_cs_robot_driver/script_node"
echo ""
echo "• 安全关节运动示例:"
echo "   ~/elite_ros_ws/install/eli_cs_robot_driver/lib/eli_cs_robot_driver/example_safe_joint_move"
echo ""
echo "• 校准工具:"
echo "   ~/elite_ros_ws/install/eli_cs_robot_calibration/lib/eli_cs_robot_calibration/calibration_correction"
echo ""
echo "📁 重要配置文件位置:"
echo ""
echo "• 机器人描述: ~/elite_ros_ws/install/eli_cs_robot_description/share/eli_cs_robot_description/"
echo "• 驱动程序配置: ~/elite_ros_ws/install/eli_cs_robot_driver/share/eli_cs_robot_driver/config/"
echo "• 控制器配置: ~/elite_ros_ws/install/eli_cs_controllers/share/eli_cs_controllers/"
echo "• MoveIt配置: ~/elite_ros_ws/install/eli_cs_robot_moveit_config/share/eli_cs_robot_moveit_config/"
echo "• 仿真配置: ~/elite_ros_ws/install/eli_cs_robot_simulation_gz/share/eli_cs_robot_simulation_gz/"
echo ""
echo "🔍 验证系统状态:"
echo ""
echo "• 查看所有节点: ros2 node list"
echo "• 查看所有话题: ros2 topic list"
echo "• 查看所有服务: ros2 service list"
echo "• 查看组件: ros2 component list"
echo ""
echo "⚠️  注意事项:"
echo ""
echo "1. 连接真实机器人前请确保安全措施到位"
echo "2. 首次使用建议先在仿真环境中测试"
echo "3. 根据实际机器人型号调整配置文件"
echo "4. 定期备份重要的配置文件"
echo ""
echo "📞 故障排除:"
echo ""
echo "• 检查网络连接和机器人通信"
echo "• 验证配置文件中的IP地址和端口"
echo "• 查看ROS 2日志: ros2 topic echo /rosout"
echo "• 检查硬件接口连接状态"
echo ""
echo "================================================================"
echo "                  祝您使用愉快！"
echo "================================================================"
